---
- name: Install IPA servers
  hosts: ipaserver

  roles:
  - role: ipaserver
    state: present

- name: Install IPA replicas
  hosts: ipareplicas

  roles:
  - role: ipareplica
    state: present
...
